@echo off
:loop
echo [SendifyPro] Iniciando servidor...
call npm run dev
echo [SendifyPro] El servidor se ha detenido o se esta reiniciando por una actualizacion...
echo [SendifyPro] Reiniciando en 5 segundos (Presiona Ctrl+C para cancelar)...
timeout /t 5
goto loop
